name: CD/CI
on:
  - push
jobs:
  Mkdocs-project-ci:
    runs-on: ubuntu-latest
    steps:
      - name: "Cloning repository"
        uses: actions/checkout@v3

      - name: "Listing repository files"
        run: "ls -al"
      - name: "Install python"
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: "Install dependancies"
        run: pip install -r requirements.txt
      - name: "Deploy project"
        run: mkdocs gh-deploy --force
      - name: "finish"
        run: echo " The job was successful."
