name: CD/CI
on:
  push:
    branches:
      - master
      - main
      - dev
  pull_request:
    branches:
      - master
      - main
      - dev
jobs:
  Mkdocs-project-ci:
    runs-on: ubuntu-latest
    steps:
      - name: "Cloning repository"
        uses: actions/checkout@v3

      - name: "Listing repository files"
        run: "ls -al"
      - name: "Install python"
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: "Install dependancies"
        run: pip install -r requirements.txt
      - name: "Deploy project"
        run: mkdocs gh-deploy --force
      - name: "finish"
        run: echo " The job was successful."
      - name: Login to docker
        run: docker login -u ${{ secrets.DOCKER_HUB_USER }} -p ${{ secrets.DOCKER_HUB_PASS }}
      - name: Build docker image
        run: docker build -t seriadiallo/githubaction-intro:${GITHUB_REF_NAME}  .
      - name: Push docker image
        run: docker push seriadiallo/githubaction-intro:${GITHUB_REF_NAME} 

